# Form implementation generated from reading ui file 'tvgui.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

#Handles the GUI visually and updating the GUI. The Controller and Viewer in one.

from PyQt6 import QtCore, QtGui, QtWidgets
from television_logic import Television

class Ui_main_tv(object):
    def setupUi(self, main_tv):
        """
        Creates the GUI for the TV application. Controls some layout and functionality.
        Designed in Qt Designer and created with pyqt6.
        :param main_tv:
        """
        main_tv.setObjectName("main_tv")
        main_tv.resize(851, 781)
        self.centralwidget = QtWidgets.QWidget(parent=main_tv)
        self.centralwidget.setObjectName("centralwidget")

        #calls the Television class specially as tv_main for use.
        self.tv_main = Television()

        # UI Elements
        self.channel_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.channel_display.setGeometry(QtCore.QRect(10, 10, 831, 391))
        self.channel_display.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.channel_display.setFrameShadow(QtWidgets.QFrame.Shadow.Plain)
        self.channel_display.setLineWidth(2)
        self.channel_display.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.channel_display.setObjectName("channel_display")

        #the Qlabel for the channel number display
        self.channel_num_display = QtWidgets.QLabel(parent=self.centralwidget)
        self.channel_num_display.setGeometry(QtCore.QRect(10, 470, 331, 191))
        font = QtGui.QFont()
        font.setPointSize(72)
        self.channel_num_display.setFont(font)
        self.channel_num_display.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.channel_num_display.setLineWidth(2)
        self.channel_num_display.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.channel_num_display.setObjectName("channel_num_display")

        #volume bar
        self.volume_bar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.volume_bar.setGeometry(QtCore.QRect(357, 480, 301, 181))
        self.volume_bar.setMaximum(20)
        self.volume_bar.setProperty("value", 0)
        self.volume_bar.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.volume_bar.setObjectName("volume_bar")

        #channel up button
        self.ch_up_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ch_up_button.setGeometry(QtCore.QRect(20, 680, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ch_up_button.setFont(font)
        self.ch_up_button.setObjectName("ch_up_button")
        self.ch_up_button.clicked.connect(self.channel_up)

        #channel down button
        self.ch_down_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ch_down_button.setGeometry(QtCore.QRect(250, 680, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.ch_down_button.setFont(font)
        self.ch_down_button.setObjectName("ch_down_button")
        self.ch_down_button.clicked.connect(self.channel_down)

        #volume up button
        self.vol_up_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vol_up_button.setGeometry(QtCore.QRect(360, 680, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.vol_up_button.setFont(font)
        self.vol_up_button.setObjectName("vol_up_button")
        self.vol_up_button.clicked.connect(self.volume_up)

        #volume down button
        self.vol_down_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.vol_down_button.setGeometry(QtCore.QRect(570, 680, 81, 81))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.vol_down_button.setFont(font)
        self.vol_down_button.setObjectName("vol_down_button")
        self.vol_down_button.clicked.connect(self.volume_down)

        #power button
        self.power_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.power_button.setGeometry(QtCore.QRect(680, 430, 151, 151))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.power_button.setFont(font)
        self.power_button.setObjectName("power_button")
        self.power_button.clicked.connect(self.toggle_power)

        #mute button
        self.mute_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.mute_button.setGeometry(QtCore.QRect(680, 610, 151, 151))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.mute_button.setFont(font)
        self.mute_button.setObjectName("mute_button")
        self.mute_button.clicked.connect(self.toggle_mute)

        #Channel control title
        self.channel_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.channel_title.setGeometry(QtCore.QRect(130, 680, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.channel_title.setFont(font)
        self.channel_title.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.channel_title.setLineWidth(2)
        self.channel_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.channel_title.setObjectName("channel_title")

        #volume control title
        self.volume_title = QtWidgets.QLabel(parent=self.centralwidget)
        self.volume_title.setGeometry(QtCore.QRect(460, 680, 91, 81))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.volume_title.setFont(font)
        self.volume_title.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.volume_title.setLineWidth(2)
        self.volume_title.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.volume_title.setObjectName("volume_title")

        # NAME OF CHANNEL DISPLAY TITLE THING
        self.channel_name = QtWidgets.QLabel(parent=self.centralwidget)
        self.channel_name.setGeometry(QtCore.QRect(10, 420, 331, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.channel_name.setFont(font)
        self.channel_name.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.channel_name.setLineWidth(2)
        self.channel_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.channel_name.setObjectName("channel_name")

        # VOLUME LEVEL TITLE
        self.channel_name_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.channel_name_2.setGeometry(QtCore.QRect(360, 420, 301, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.channel_name_2.setFont(font)
        self.channel_name_2.setFrameShape(QtWidgets.QFrame.Shape.WinPanel)
        self.channel_name_2.setLineWidth(2)
        self.channel_name_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.channel_name_2.setObjectName("channel_name_2")
        main_tv.setCentralWidget(self.centralwidget)

        main_tv.setCentralWidget(self.centralwidget)
        self.retranslateUi(main_tv)
        self.update_display()
        QtCore.QMetaObject.connectSlotsByName(main_tv)

    def retranslateUi(self, main_tv) -> None:
        """
        Translates the GUI buttons, titles, and labels.
        :param main_tv:
        """
        _translate = QtCore.QCoreApplication.translate
        main_tv.setWindowTitle(_translate("main_tv", "PY TV"))
        self.channel_name.setText(_translate("main_tv", None))
        self.channel_num_display.setText(_translate("main_tv", "1"))
        self.ch_up_button.setText(_translate("main_tv", "+"))
        self.ch_down_button.setText(_translate("main_tv", "-"))
        self.channel_title.setText(_translate("main_tv", "CHANNEL"))
        self.power_button.setText(_translate("main_tv", "POWER"))
        self.mute_button.setText(_translate("main_tv", "MUTE"))
        self.vol_down_button.setText(_translate("main_tv", "-"))
        self.vol_up_button.setText(_translate("main_tv", "+"))
        self.volume_title.setText(_translate("main_tv", "VOLUME"))
        self.channel_name_2.setText(_translate("main_tv", None))


    def update_display(self) -> None:
        """
        Updates the GUI based on various statuses.
        """
        #Basically if TV is on do these things.
        # If, else, back and forth to determine what should be displayed when TV is powered on.
        if self.tv_main._Television__status:

            self.channel_num_display.setText(str(self.tv_main._Television__channel))

            #Update volume/mute status
            if self.tv_main._Television__muted:
                self.channel_name_2.setText("MUTED")

            else:  #If not muted show the volume level
                self.channel_name_2.setText("VOLUME LEVEL")

            self.volume_bar.setValue(self.tv_main._Television__volume)

            #Update the channel display with channel image.
            channel_data = self.tv_main.get_status()["channel_data"]
            image_path = channel_data["image"]


            if image_path:
                pixmap = QtGui.QPixmap(image_path)
                self.channel_display.setPixmap(pixmap)

            else:
                self.channel_display.clear()

            #Update the channel name/title
            channel_name = channel_data["name"]
            self.channel_name.setText(channel_name)

        else:  #If the TV is OFF
            self.channel_num_display.setText("OFF")
            self.volume_bar.setValue(0)
            self.channel_name_2.setText("VOLUME LEVEL")
            self.channel_display.clear()
            self.channel_name.setText("")

    def toggle_power(self) -> None:
        """
        Changes the power status of the television, and lets the display know
        """
        self.tv_main.power()
        self.update_display()

    def toggle_mute(self) -> None:
        """
        Changes the mute status of the television and lets the display know.
        """
        self.tv_main.mute()
        self.update_display()

    def channel_up(self)-> None:
        """
        Changes the channel up 1 and lets the display know.
        """
        self.tv_main.channel_up()
        self.update_display()

    def channel_down(self)-> None:
        """
        Changes the channel down 1 and lets the display know.
        """
        self.tv_main.channel_down()
        self.update_display()

    def volume_up(self)-> None:
        """
        Increases the volume and lets the display know.
        """
        self.tv_main.volume_up()
        self.update_display()

    def volume_down(self)-> None:
        """
        Decreases the volume and lets the display know.
        """
        self.tv_main.volume_down()
        self.update_display()